// Generated by CoffeeScript 1.10.0
var lightning;

lightning = function() {
    $('#container .lightning').fadeIn(250).fadeOut(250);
    return setTimeout('lightning()', 2000);
};

$(document).ready(function() {
    var eyesIndex, headIndex, mouthIndex, noseIndex;
    lightning();
    headIndex = 0;
    eyesIndex = 0;
    noseIndex = 0;
    mouthIndex = 0;
    $('#head').click(function() {
        if (headIndex < 9) {
            $(this).animate({
                left: '-=367px'
            }, 500);
            headIndex += 1;
        } else {
            headIndex = 0;
            $(this).animate({
                left: 0
            }, 500);
        }
    });
    $('#eyes').click(function() {
        if (eyesIndex < 9) {
            $(this).animate({
                left: '-=367px'
            }, 500);
            eyesIndex += 1;
        } else {
            eyesIndex = 0;
            $(this).animate({
                left: 0
            }, 500);
        }
    });
    $('#nose').click(function() {
        if (noseIndex < 9) {
            $(this).animate({
                left: '-=367px'
            }, 500);
            noseIndex += 1;
        } else {
            noseIndex = 0;
            $(this).animate({
                left: 0
            }, 500);
        }
    });
    $('#mouth').click(function() {
        if (mouthIndex < 9) {
            $(this).animate({
                left: '-=367px'
            }, 500);
            mouthIndex += 1;
        } else {
            mouthIndex = 0;
            $(this).animate({
                left: 0
            }, 500);
        }
    });
});
